# theme: jekyll-theme-midnight
remote_theme: DigitalMindCH/gridster-jekyll-theme
# remote_theme: yous/whiteglass-template
title: McFisch's Blog
author: Mario Fischer
description: Mario sharing thoughts, notes, projects etc.
