title: McFiscH's Blog
author: Mario Fischer
description: >- # this means to ignore newlines until "baseurl:"
  It's Mario, sharing thoughts, notes, projects etc.
baseurl:
url: "https://blog-test.mcfisch.com"
lang: en
timezone: America/Los_Angeles # need to check if this works

# Social media
twitter_username: systemfisch
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false

# Build settings
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - README.md

# Outputting
permalink: /:year/:month/:day/:title/

# Markdown settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# jekyll-paginate
paginate_path: /posts/:num/
paginate: 5
