# theme: jekyll-theme-dinky
# remote_theme: DigitalMindCH/gridster-jekyll-theme
remote_theme: yous/whiteglass
title: McFisch's Blog
author: Mario Fischer
description: It's Mario, sharing thoughts, notes, projects etc.
show_downloads: false
